sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jagasan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jagasan/react-test npm test

after_success:
  - docker build -t jagasan/multi-client ./client
  - docker build -t jagasan/multi-nginx ./nginx
  - docker build -t jagasan/multi-server ./server
  - docker build -t jagasan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jagasan/multi-client
  - docker push jagasan/multi-nginx
  - docker push jagasan/multi-server
  - docker push jagasan/multi-worker

  #AWS deployment configuration in Travis
deploy:
#AWS container name 
  provider: elasticbeanstalk
#AWS regin check created url 
  region: "us-west-2"
#AWS created application name
  app: "multi-docker"
#AWS created enviornment name
  env: "Multidocker-env"
#EC2 bucket name search ec2 
  bucket_name: "elasticbeanstalk-us-west-2-110656221591"
 #EC2 bucket path name same as application name by default 
  bucket_path: "multi-docker"

#git branch
  on:
    branch: master
#AWS create user with permission and set those secret key and access key 
#in Tracvis application enviornment variable 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

